### ISSUE TITLE
Publish this somewhere it can be downloaded and unzipped

### ISSUE THREAD

**Issue by kadenzipfel** [PaulRBerg/cea-template#6]
A simple npm package?

**Comment by PaulRBerg** [comment]
Done! See my `downloadAndExtractTemplate` function here:

https://github.com/PaulRBerg/create-eth-app/blob/develop/src/helpers/template.ts

Read more about codeloag.github.com here:

https://stackoverflow.com/questions/60188254/how-is-codeload-github-com-different-to-api-github-com
